import { Mood } from '../types';

// Positive responses (LiLi) - for HAPPY, SMART, DANCING moods
const POSITIVE_RESPONSES = [
  "LiLi happy!",
  "LiLi love you!",
  "LiLi feel good!",
  "LiLi so round!",
  "LiLi want lasagna!",
  "LiLi best goose!",
  "LiLi feel great!",
  "LiLi so soft!",
  "LiLi love pets!",
  "LiLi feel warm!",
  "LiLi so fluffy!",
  "LiLi want play!",
  "LiLi feel strong!",
  "LiLi love food!",
  "LiLi so happy!",
  "LiLi feel good!",
  "LiLi want hug!",
  "LiLi so cute!",
  "LiLi feel safe!",
  "LiLi love owner!",
  "LiLi want snack!",
  "LiLi so round!",
  "LiLi feel great!",
  "LiLi love fun!",
  "LiLi want dance!",
  "LiLi so happy!",
  "LiLi feel good!",
  "LiLi want cuddle!",
  "LiLi so soft!",
  "LiLi feel warm!",
  "LiLi love treats!",
  "LiLi want play!",
  "LiLi so fluffy!",
  "LiLi feel strong!",
  "LiLi love you!",
  "LiLi want lasagna!",
  "LiLi so round!",
  "LiLi feel great!",
  "LiLi love pets!",
  "LiLi want snack!",
  "LiLi so happy!",
  "LiLi feel good!",
  "LiLi love food!",
  "LiLi want hug!",
  "LiLi so cute!",
  "LiLi feel safe!",
  "LiLi love owner!",
  "LiLi want dance!",
  "LiLi so round!",
  "LiLi feel great!",
  "LiLi love fun!",
];

// Negative responses (LoLo) - for MAD, SLEEPY moods
const NEGATIVE_RESPONSES = [
  "LoLo tired...",
  "LoLo hungry now!",
  "LoLo not happy!",
  "LoLo want sleep!",
  "LoLo feel bad!",
  "LoLo so grumpy!",
  "LoLo need food!",
  "LoLo too sleepy!",
  "LoLo not good!",
  "LoLo want rest!",
  "LoLo feel weak!",
  "LoLo so tired!",
  "LoLo need help!",
  "LoLo not fun!",
  "LoLo want bed!",
  "LoLo feel sad!",
  "LoLo so grumpy!",
  "LoLo need snack!",
  "LoLo too sleepy!",
  "LoLo not happy!",
  "LoLo want sleep!",
  "LoLo feel bad!",
  "LoLo so tired!",
  "LoLo need food!",
  "LoLo not good!",
  "LoLo want rest!",
  "LoLo feel weak!",
  "LoLo so grumpy!",
  "LoLo need help!",
  "LoLo not fun!",
  "LoLo want bed!",
  "LoLo feel sad!",
  "LoLo too sleepy!",
  "LoLo not happy!",
  "LoLo want sleep!",
  "LoLo feel bad!",
  "LoLo so tired!",
  "LoLo need food!",
  "LoLo not good!",
  "LoLo want rest!",
  "LoLo feel weak!",
  "LoLo so grumpy!",
  "LoLo need help!",
  "LoLo not fun!",
  "LoLo want bed!",
  "LoLo feel sad!",
  "LoLo too sleepy!",
  "LoLo not happy!",
  "LoLo want sleep!",
  "LoLo feel bad!",
  "LoLo so tired!",
];

// Wisdom responses (mix of LiLi and LoLo based on context)
const WISDOM_RESPONSES = [
  "LiLi think lasagna best food!",
  "LiLi know round is good shape!",
  "LiLi think sleep is important!",
  "LiLi know love makes happy!",
  "LiLi think food is friend!",
  "LiLi know soft things feel nice!",
  "LiLi think round goose is best!",
  "LiLi know happy is good!",
  "LiLi think lasagna makes strong!",
  "LiLi know round means cozy!",
  "LiLi think food is magic!",
  "LiLi know love is warm!",
  "LiLi think round is perfect!",
  "LiLi know happy goose is best!",
  "LiLi think lasagna is treasure!",
  "LiLi know round means safe!",
  "LiLi think food makes joy!",
  "LiLi know soft is comfort!",
  "LiLi think round goose is smart!",
  "LiLi know happy is life!",
  "LiLi think lasagna is power!",
  "LiLi know round means love!",
  "LiLi think food is friend!",
  "LiLi know soft things heal!",
  "LiLi think round is wisdom!",
  "LiLi know happy goose wins!",
  "LiLi think lasagna is key!",
  "LiLi know round means peace!",
  "LiLi think food is answer!",
  "LiLi know soft is strength!",
  "LiLi think round goose knows!",
  "LiLi know happy is truth!",
  "LiLi think lasagna is light!",
  "LiLi know round means home!",
  "LiLi think food is hope!",
  "LiLi know soft is power!",
  "LiLi think round is beauty!",
  "LiLi know happy goose rules!",
  "LiLi think lasagna is dream!",
  "LiLi know round means joy!",
  "LiLi think food is love!",
  "LiLi know soft is magic!",
  "LiLi think round goose sees!",
  "LiLi know happy is all!",
  "LiLi think lasagna is star!",
  "LiLi know round means heart!",
  "LiLi think food is gift!",
  "LiLi know soft is truth!",
  "LiLi think round is everything!",
  "LiLi know happy goose flies!",
];

// Story start responses
const STORY_STARTS = [
  "Once upon a time...",
  "Long ago there was...",
  "In a far away place...",
  "Once there lived...",
  "Long time ago...",
  "In a magical world...",
  "Once in a land...",
  "Long ago in...",
  "In a cozy nest...",
  "Once a goose...",
  "Long time past...",
  "In a happy place...",
  "Once upon a day...",
  "Long ago lived...",
  "In a round world...",
  "Once there was...",
  "Long time before...",
  "In a soft place...",
  "Once a round goose...",
  "Long ago found...",
  "In a warm nest...",
  "Once upon a dream...",
  "Long time ago lived...",
  "In a cozy world...",
  "Once there lived a...",
  "Long ago in time...",
  "In a happy nest...",
  "Once upon a round...",
  "Long time past lived...",
  "In a magical place...",
];

// Get random response from array
const getRandomResponse = (responses: string[]): string => {
  return responses[Math.floor(Math.random() * responses.length)];
};

export const generateGooseWisdom = async (): Promise<string> => {
  return getRandomResponse(WISDOM_RESPONSES);
};

export const generateStoryStart = async (): Promise<string> => {
  return getRandomResponse(STORY_STARTS);
};

export const generateRandomChat = async (mood: string): Promise<string> => {
  // Map mood to positive or negative
  const isPositive = mood === Mood.HAPPY || mood === Mood.SMART || mood === Mood.DANCING;
  
  if (isPositive) {
    return getRandomResponse(POSITIVE_RESPONSES);
  } else {
    return getRandomResponse(NEGATIVE_RESPONSES);
  }
};
